development:
  adapter: sqlite3
  database: db/app.sqlite3
  pool: 5
  timeout: 5000
  
production:
  adapter: sqlite3
  database: db/app.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/app_test.sqlite3
  pool: 5
  timeout: 5000